#!/bin/sh

# simplify git command for working with my dotfiles
function config {
  git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
}

# if my dotfile repo hasn't been cloned, then do that
[[ ! -e $HOME/.dotfiles ]] && \
  git clone --bare git@github.com:bradyslot/dotfiles.git $HOME/.dotfiles

# I only care about files I've added myself
config config status.showUntrackedFiles no

# get the latest dotfiles from remote
config fetch --all
config reset --hard dotfiles/master

# clone my forks
[[ ! -e $HOME/src ]] && mkdir $HOME/src
cd $HOME/src
git clone git@github.com:bradyslot/dwm.git
git clone git@github.com:bradyslot/dmenu.git
git clone git@gitbug.com:bradyslot/dwmblocks.git

# build and install my forks
cd dwm; sudo make clean install; cd ..
cd dmenu; sudo make clean install; cd ..
cd dwmblocks; sudo make clean install; cd ..
cd $HOME
