#!/bin/sh

audio() {
	pulsemixer --get-mute | sed -e 's/0/ /' -e 's/1/ /' | tr -d '\n'
	pulsemixer --get-volume | awk '{print $1}'
}

datetime() {
	echo " " | tr -d '\n'
	date '+%b %d %I:%M%p'
}

link() {
	ping -q -c 1 1.1.1.1 > /dev/null 2>&1 && echo " " || echo " "
}

memory() {
	echo " " | tr -d '\n'
	free -m | awk 'NR==2{print $3}' | tr -d '\n' 
	echo "mb"
}

temperature() {
	echo "﬙ " | tr -d '\n'
	sensors coretemp-isa-0000 | awk 'NR==3{gsub("+","");print $4}'
}

weather() {
	curl -s wttr.in/3189?format=1 | sed 's/ //'
}

genstatus() {
	printf -v status "| %s | %s | %s | %s | %s | %s |" \
	"$audio_stdo" "$link_stdo" "$memory_stdo" "$temperature_stdo" "$weather_stdo" "$datetime_stdo" 
}

drawstatus() {
    xsetroot -name "$(echo $status | tr -d '\n')"
}

test() {
    filename="$1"
    current="$($1)"
	eval previous='$'${filename}_stdo
	
    if [ "$current" != "$previous" ]; then
        refr="yes"
    fi

    eval "${filename}_stdo='$current'"
}

i=0
while :; do
    # update every 1 second
    if (( $i%1 == 0 )); then
		test audio
    fi

    # update every 5 seconds
    if (( $i%5 == 0 )); then
		test temperature
		test memory
    fi

    #update every 10 seconds
    if (( $i%10 == 0 )); then
		test datetime
		test link
    fi

    #update every 10 minutes
    if (( $i%600 == 0 )); then
		test weather
    fi

    if [ "$refr" = "yes" ]; then
        genstatus
        drawstatus
        refr="no"
    fi

    (( i++ ))
    sleep 1
done

